#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# browser
export BROWSER=chromium

# user path
export PATH="$PATH:$HOME/bin"

# npm-global
export PATH="$PATH:$HOME/.npm-global/bin"

# nvm
source /usr/share/nvm/init-nvm.sh

# rust
source $HOME/.cargo/env
export RUST_SRC_PATH=$HOME/src/rust/src
export CARGO_HOME=$HOME/.cargo

